api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: '%pagination.default_items_per_page%'
        pagination_maximum_items_per_page: '%pagination.max_items_per_page%'
        pagination_client_items_per_page: true
        pagination_client_page: true
