# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    rate_limiter:
        auth_register:
            policy: 'fixed_window'
            limit: 20
            interval: '1 minute'
        auth_login:
            policy: 'fixed_window'
            limit: 10
            interval: '1 minute'
        auth_refresh:
            policy: 'fixed_window'
            limit: 30
            interval: '1 minute'
        auth_pwd_request:
            policy: 'fixed_window'
            limit: 20
            interval: '1 minute'
    secret: '%env(APP_SECRET)%'

    # CSRF protection for API endpoints
    csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        cookie_httponly: true

    # Trusted proxies configuration for proper HTTPS detection behind reverse proxy
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers:
        - x-forwarded-for
        - x-forwarded-proto
        - x-forwarded-port
        - x-forwarded-host

    #esi: true
    #fragments: true
    error_controller: 'error_controller'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
