# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    cache: default
    webp:
        generate: false
        quality: 80
    filter_sets:
        cache: ~

        sm:
            quality: 50
            filters:
                thumbnail:
                    size: [ 150, 150 ]
                    mode: inset
                scale:
                    dim: [ 150, 150 ]
                background:
                    size: [ 150, 150 ]
                    position: center
                    color: '#fff'
        md:
            quality: 65
            filters:
                thumbnail:
                    size: [ 330, 330 ]
                    mode: inset
                scale:
                    dim: [ 330, 330 ]
                background:
                    size: [ 330, 330 ]
                    position: center
                    color: '#fff'
        md2:
            quality: 80
            filters:
                thumbnail:
                    size: [ 700, 700 ]
                    mode: inset
                    allow_upscale: true
                scale:
                    dim: [700, 700]
                background:
                    size: [ 700, 700 ]
                    position: center
                    color: '#fff'
        xl:
            quality: 80
            filters:
                thumbnail:
                    size: [ 1200, 1200 ]
                    mode: inset
                    allow_upscale: true
                scale:
                    dim: [ 1200, 1200 ]
                background:
                    size: [ 1200, 1200 ]
                    position: center
                    color: '#fff'




