monolog:
    channels: ['app', 'security', 'doctrine', 'request', 'deprecation', 'idempotency']
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event', '!doctrine', '!security']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!security']
        doctrine:
            type: stream
            path: '%kernel.logs_dir%/doctrine_%kernel.environment%.log'
            level: debug
            channels: [doctrine]
        security:
            type: stream
            path: '%kernel.logs_dir%/security_%kernel.environment%.log'
            level: info
            channels: [security]
        request:
            type: stream
            path: '%kernel.logs_dir%/request_%kernel.environment%.log'
            level: info
            channels: [request]
        deprecation:
            type: stream
            path: '%kernel.logs_dir%/deprecation_%kernel.environment%.log'
            level: info
            channels: [deprecation]
        idempotency:
            type: stream
            path: '%kernel.logs_dir%/idempotency_%kernel.environment%.log'
            level: info
            channels: [idempotency]
