parameters:
    # Общие настройки (используются для товаров и по умолчанию)
    pagination.items_per_page_options: [10, 20, 40]
    pagination.default_items_per_page: 10

    # Настройки для City
    pagination.city.items_per_page_options: [30, 60, 100]
    pagination.city.default_items_per_page: 30

    # Технический максимум для API Platform (глобально)
    pagination.max_items_per_page: 100

    # Настройки для Pvz (админ)
    pagination.pvz.items_per_page_options: [30, 60, 100]
    pagination.pvz.default_items_per_page: 30


