php bin/console liip:imagine:cache:resolve img/potolok/kapel/613A6665.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/potolok/kapel/613A6667.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/potolok/kapel/613A6680.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/potolok/kapel/613A6682.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/potolok/kapel/613A6684.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/potolok/photo_2025-08-13_12-05-25.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/anzhelika-3-lampy-niz-1-zoloto-1.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/astra-buton-1-pod-bronzu-chernaya-1.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/astra-buton-1-pod-bronzu-zelenaya-1.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/DeWatermark.ai_1755076284277.jpeg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/diana-6-zhuravlik-pod-bronzu-1.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/diana-6-zhuravlik-pod-bronzu-chaynaya-1.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/diana-6-zhuravlik-pod-bronzu-zelenaya-1.jpg --filter=md --filter=md2
php bin/console liip:imagine:cache:resolve img/photo_2025-08-13_12-05-25.jpg --filter=md --filter=md2
